baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '希爾的家'
theme = "hugo-theme-stack"
[menu]
  [[menu.main]]
    identifier = "about"
    name = "關於我"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "home"
    name = "HOME"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "Friends"
    name = "部落格友列"
    url = "/Friends/"
    weight = 10
  [[menu.main]]
    identifier = "Findme"
    name = "聯絡我"
    url = "/Findme/"
    weight = 10