baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"
[menu]
  [[menu.main]]
    identifier = "about"
    name = "關於我"
    url = "/about/"
    weight = 10