baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '希爾的家'
theme = "PaperMod"
[menu]
  [[menu.main]]
    identifier = "about"
    name = "關於我"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "home"
    name = "HOME"
    url = "/"
    weight = 5